# -*- coding: utf-8 -*-
"""text_processor.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8AVgMornaiwznE6r2A9r8LPiREX_zvL
"""

# text_processor.py  Z.Bour


import re
import json
import string

class TextProcessor:
    def __init__(self, input_file_path, output_file_path='word_frequencies.json'):
        self.input_file_path = input_file_path
        self.output_file_path = output_file_path
        self.text = ''
        self.cleaned_text = ''
        self.words = []
        self.filtered_words = []
        self.word_frequencies = {}

        self.stopwords = set([
            "و", "در", "به", "از", "که", "این", "را", "با", "است", "برای", "آن",
            "یک", "هم", "تا", "نیز", "اما", "یا", "بر", "اگر", "هر", "چون", "باید",
            "می", "شد", "کند", "کرد", "شده", "دیگر", "همه", "نیک", "اینجا", "اینها", "آنان", "خود"
        ])

    def file_read(self):
        with open(self.input_file_path, 'r', encoding='utf-8') as file:
            self.text = file.read()

    def text_clean(self):
        # getting rid of emails
        self.cleaned_text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '', self.text)

        # deleting links
        self.cleaned_text = re.sub(r'https?://\S+|www\.\S+', '', self.cleaned_text)

        # omitting punctuation
        punctuation_pattern = r'[{}]'.format(re.escape(string.punctuation + '«»؛؟،٫٬'))
        self.cleaned_text = re.sub(punctuation_pattern, '', self.cleaned_text)

        # splitting
        self.words = self.cleaned_text.split()

    def stopwords_remove(self):
        self.filtered_words = [word for word in self.words if word not in self.stopwords]

    def frequencies_word_count(self):
        for word in self.filtered_words:
            self.word_frequencies[word] = self.word_frequencies.get(word, 0) + 1

    def json_to_save(self):
        with open(self.output_file_path, 'w', encoding='utf-8') as json_file:
            json.dump(self.word_frequencies, json_file, ensure_ascii=False, indent=4)

    def process(self):
        self.file_read()
        self.text_clean()
        self.stopwords_remove()
        self.frequencies_word_count()
        self.json_to_save()


# to run the program:
processor = TextProcessor("input.txt")
processor.process()